# This is a basic workflow to help you get started with Actions

name: Run Action One Time

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3
      - name: Download file
        run: |
          echo "Starting the download"
          wget https://download.moodle.org/environment/environment.zip -O environment.zip
          echo "Download completed"
      # - name: Create branch
      #   run: |
      #     echo "Setup username"
      #     git config --global user.email "neeraj.nanvani@vidyamantra@github.com"
      #     git config --global user.name "neerajnanvani"
      #     echo "username setup"
      #     pwd
      #     ls -a
      #     git checkout -b add-file
      #     git add environment.zip
      #     git commit -m "Add file.txt"
      #     echo "Commit the file done"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Add file.txt'
          # base: main
          branch: add-file
          title: 'Add file.txt'
          body: 'Add file.txt'
          labels: 'file'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        if: steps.create_pr.outputs.pull-request-number
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          PULL_REQUEST: ${{ steps.create_pr.outputs.pull-request-number }}
          MERGE_METHOD: "squash"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"