name: Store in cache

# Controls when the workflow will run
on:
  
  workflow_dispatch: 

# run all jobs one by one
jobs:
  run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3

      - name: Download plugin Versions file
        run: |
          echo "Starting the download"
          wget https://raw.githubusercontent.com/jonof/moodle-antivirus_savdi/master/version.php -O pluginVersion.php
          echo "Download completed"

      - name: Store data in cache
        uses: actions/cache@v3
        with:
          key: pluginVersion
          path: pluginVersion.php

      - name: Retrieve data from cache
        run: |
          cached_data_path=$HOME/.cache/pluginVersion/pluginVersion.php
          if [ -f "$cached_data_path" ]; then
            cached_data=$(cat "$cached_data_path")
            echo "Cached data: $cached_data"
            cp "$cached_file_path" ./
          else
            echo "Cached file not found."
            exit 1
          fi
      
      - name: Current directory
        run: ls & pwd
      


